"""empty message

Revision ID: cfedd9955198
Revises: 13bee806be84
Create Date: 2020-04-17 00:37:07.044207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfedd9955198'
down_revision = '13bee806be84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beizhu', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('dep', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_time', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_last_time'), ['last_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_last_time'))
        batch_op.drop_column('last_time')
        batch_op.drop_column('dep')
        batch_op.drop_column('beizhu')

    # ### end Alembic commands ###
